jupyter-incubator/dashboards_server

Dockerfile.kernel, Makefile, README.md
Paired with @nitind to create some make targets that will run/kill tmpnb containers (proxy and pool).  Currently, the targets can be used to launch tmpnb separately from kernel_gateway container.  
To run tmpnb:
`make run-tmpnb TOKEN=mytoken`
To kill:
`make kill-tmpnb`
Have not changed the `make run` target -- it still runs kernel_gateway container.  We can look at switching to tmpnb (instead of kernel_gateway) once the node app has more support for running against tmpnb.
One final note: had to switch the ENTRYPOINT and CMD args in Dockerfile.kernel due to tmpnb always running command using `/bin/sh -c` (see https://github.com/jupyter/tmpnb/issues/209).
=> Add make targets for running tmpnb containers

Makefile
Decrease sleep time.
Add logging for major targets.
=> Don't run build twice on `integration-test` target

bower.json, gulpfile.js
lodash v4.0+ breaks gridstack rendering. For now,
lock to below 4.0.
Refs #10
=> Lock lodash version to below 4.0

Makefile, routes/api.js
In order to proxy across domains, we need to rewrite original request headers, such as `host`, `hostname`, `protocol`.   
See https://github.com/nodejitsu/node-http-proxy#options
=> Rewrite request headers 

routes/api.js, test/base/routes/api-test.js
We are deleting kernels by invoking the kernel gateway API, but the code was using the `http` module, which does not work if kernel gateway is running over https.   
Switch to requests, which handles both http and https protocols.
=> Delete kernels over http and https protocols

app/handlebars-helpers.js, config.json, less/login.less, public/js/dashboard.js, routes/login.js, routes/routes.js, views/dashboard.handlebars, views/login.handlebars, views/partials/nav.handlebars, views/partials/welcome.handlebars
Adds `config` handlebars helper and uses it to fill in default dashboard parameters. 
I went ahead and made use of this to remove the pervasive `authEnabled` flag being used on many template renders.
I also renamed the global `Urth` object to `Config` in the dashboard page since I was editing that template. This looked like the only use of "urth" outside of reading the notebook files.
Fixes #69
=> [Issue 69] Read default dashboard parameters from config.

gulpfile.js, package.json, views/layouts/main.handlebars
We weren't actually using it, it didn't actually work, and it caused a client-side error when running in a container.
=> [Dev] Remove livereload script from dev dependencies.

less/dashboard.less
=> [Issue 71] Match notebook style: max image width and text cell overflow.

gulpfile.js, package.json
=> [Issue 67] Use jupyter-js-notebook for output area.

routes/routes.js
This puts us at same level as Notebook, where title of the notebook is the name of the file.
Further work could be done to pull a more descriptive title from first header in notebook's first cell, but we would diverge from (classic) Jupyter Notebook.
Fixes #90
=> Set name of dashboard browser path based on filename

public/js/kernel.js
Makes it so notebook names with spaces in them aren't evaluated
with a "%20" instead of a space.
Fixes #111
=> Pass along decoded notebook path

public/js/dashboard.js, views/dashboard.handlebars
We were using DOM order. Added data-cell-index attr to sort cells in notebook order.
Resolves #56
=> [Issue 56] Ensure notebook order when executing cells.

app/config.js, config.json, routes/api.js, test/base/routes/api-test.js
Fixes #31. Subsumes #142 to move config location.
=> [Issue: 31] Allow dashboard clients to reconnect to running kernel

Dockerfile.kernel
No longer needed because we don't need/want to build the ipywidgets JS in this image, and only need the Python
=> Remove npm from kernel gateway image

.dockerignore, Dockerfile.kernel, Dockerfile.server, app.js, config.json, etc/notebooks/test/test_env_vars.ipynb, public/js/kernel.js, routes/api.js, test/base/routes/api-test.js
Damn near impossible to modify the outgoing body of a proxied request which is what #168 requires. So ...
* Move kernel creation logic to a standard route
* Move all special case tracking performed after kernel creation to that route
* Inject auth info if `KG_FORWARD_USER_AUTH` is set (PS: don't assign to a module global like the others since we want to vary it during testing)
* Upgrade kernel gateway to 0.5.0 for env var support
* Add a test notebook/dashboard that print all env vars for manual testing
* Add unit tests
Fixes #168
=> [issue: 168] Option to pass user auth to kernel

.dockerignore, routes/api.js, test/base/routes/api-test.js
* Don't pass all request headers to /api/kernels to avoid
ping-ponging requests when Host/Origin are unexpected
* Fix random test failures by stubbing request.Request so that
async callbacks we don't care about never happen
* Fix integration test breakage: integration-test requires
etc/notebooks for the docker build so we can't ignore it
=> Fix problems from #168

app/config.js, routes/renderers.js, routes/routes.js
* If a directory contains a folder named index which itself contains an index.ipynb, redirect to it immediately in place of showing a directory listing (i.e., makes bundled dashboards named index behave like unbundled dashboards named index.ipynb)
* Allow access to /dashboards/* under /* by adjusting route ordering and patterns slightly (previously, only the root (/) listing or index.ipynb was accessible without /dashboards)
* Comment the hell out of the renderer.render logic
Fixes #178
=> [issue: 178] Immediately load index/index.ipynb bundles

etc/notebooks/test/test_plotting_libs.ipynb
Update the pip install of plotly to use the default version.
Fixes #177
=> [Issue: 177] Update test_plotting_libs notebook Plotly install

public/js/dashboard.js
Delay the firing of the kernel_ready.Kernel event until the
kernel has reached idle status. Fixes a race condition found
in the development version of the declarativewidgets
extension.
(c) Copyright IBM Corp. 2016
=> [Issue: 141] delay firing the kernel_ready.Kernel event

less/notebook.less
Adopt the auto margin values from the notebook for rendered img
elements.
(c) Copyright IBM Corp. 2016
=> [Issue: 146] <img> styling differs from Notebook

app/ws-rewriter.js
Otherwise, WebSocketConnection will just error out instead
of actually closing the connection.
=> Validate socket close code

app/config.js
Otherwise path to config is computed relative to cwd
which will likely be incorrect when run from an npm install
=> Fix relative path to config.json

Makefile, app/append-ext.js, app/config.js, app/notebook-fs.js, app/notebook-store.js, app/notebook-upload.js, config.json, gulpfile.js, routes/auth-routes.js, routes/renderers.js, test/base/app/upload-notebook-test.js
`notebook-store.js` contained several utility functions that should be individual modules. I've split it apart accordingly and cleaned up the code a bit.
This also includes the addition of a public dashboard link which is used in https://github.com/jupyter-incubator/dashboards_bundlers/pull/37.
=> [Enhancement] Split notebook-store into multiple modules

client/less/dashboard.less
Causes page to always be taller than viewport, resulting
in unnecessary scrollbar for short pages.
=> Remove antiquated '100vh' rule

Makefile, app/config.js, app/public-link.js, config.json, routes/auth-routes.js
Allows {protocol}, {hostname}, and {port} placeholders in a PUBLIC_LINK_PATTERN config parameter
Upload API will build the public link based on this pattern and omit the link if the pattern is not set in the config
Resolves #218
=> [Issue 218] Make public link a customizable pattern

client/less/notebook.less
=> [Issue: 221] matplotlib image is centered in dashboard server, left-justified in notebook

client/js/layout.js, etc/notebooks/test/test_padding.ipynb
Dashboard preview in the 0.5.2 layout extension (which uses Gridstack) does not include any extra padding on cells:
Our read-only Gridstack-light clone here in dashboard server dynamically adds padding which causes full cells to overflow and misalign (see right edge of table):
This PR removes the extra padding. @jhpedemonte, @dalogsdon any reason why it should remain?
=> Fix extraneous cell padding

Dockerfile.kernel
For parity with other dev environments to reduce docker pulls
=> Bump to notebook 4.2 in kernel image

client/less/dashboard.less
Fixes jupyter-incubator/dashboards#278
Since cells are absolutely positioned, they don't affect the size of their parent/ancestor elements. This meant that `body` was quite small. The code that shows the dropdown menus would check if there was enough space to show below the widget; if not, it would show the menu above. This check was always showing not enough space. This change will set body to always take up at least the full viewport height.
=> Sets body height to prevent "dropup" menus

views/partials/nav.handlebars
Handle the default case where baseUrl is empty. Otherwise, it just links back to the current page.
=> Fix regression in title link nav
