.gitignore
app.js
app/config.js
app/handlebars-helpers.js
app/notebook-store.js
app/ws-utils.js
bin/www
bower.json
config.json
gulpfile.js
less/dashboard-common.less
less/dashboard.less
less/gridstack-overrides.less
less/style.less
package.json
public/js/dashboard.js
public/js/gridstack-custom.js
public/js/kernel.js
public/js/main.js
routes/api.js
routes/index.js
views/dashboard.handlebars
views/error.handlebars
views/index.handlebars
views/layouts/main.handlebars
views/partials/welcome.handlebars

Renders dashboard layout.
Hides code from client.

Initial implementation.

---

app/notebook-store.js
config.json
gulpfile.js
package.json
public/js/dashboard.js
public/js/kernel.js
public/js/main.js
public/js/widget-manager.js
views/dashboard.handlebars

also includes change to make notebooks directory configurable

Add support for jupyter-js-widgets (née ipywidgets)

---

.gitignore
Makefile
README.md
bin/www

[Issue 3] - Added support for https

---

.travis.yml

Fixes #12.
Should be merged after #19 since it's based on it.

[issue: 12] Enable travis

---

Dockerfile.proxy
Makefile
bin/www
config.json

[Issue 3] - Redirect http server requests to https, when in https mode.

---

Makefile
README.md

Update Makefile to start the tmpnb service by default.  Updated README too.

Start tmpnb containers in dev by default

---

Makefile
config.json
package.json
routes/api.js

[Issue 21] Support KG_BASE_URL when running kernel gateway directly

---

views/partials/nav.handlebars

[Issue 4] - Fix logout button style/position.

---

app.js
app/upload-notebook.js
package.json
routes/index.js
test/app/upload-notebook-test.js
test/base/app/upload-notebook-test.js
views/error.handlebars

Also includes error handling updates.
:chicken:
Refs #15

[Issue 15] POST /notebooks/* API

---

package.json
public/js/dashboard.js
views/dashboard.handlebars

Update output area code to latest

---

app.js
routes/index.js
routes/login.js
views/login.handlebars
views/partials/nav.handlebars

[Issue 4] - Only display login/logout button in navbar when auth is enabled.

---

Makefile
routes/api.js
test/base/routes/api-test.js

Send kernel shutdown when client websocket closes

---

routes/api.js

Definitely a bandaid, definitely not the real fix, definitely gets us over an initial hump of lost connections every 90s
Ref #50

Quick fix for missing WS pong responses

---

Makefile

[issue: 57] Clean up all dev assets on make clean

---

app.js

[Issue 37] - Suppress stack trace on 404 errors.

---

public/js/dashboard.js

[issue: 49] Send exceptions, stderr to console

---

app.js

Remove 404 and url from error message and add url to json body.

---

less/dashboard.less

[Issue 55] Add media queries to adjust dashboard width as the notebook does.

---

app.js
app/config.js
routes/api.js
routes/auth-routes.js
routes/routes.js
test/integration/auth-token/auth-token-test.js
test/integration/auth-token/kg-auth-token-test.js
test/integration/default/notebook-list-test.js
test/integration/default/upload-notebook-test.js
views/list.handlebars

Dashboard pages now under `/dashboards`
Non-kernel API routes now under `/_api`
Resolves #48

[Issue 48] Better route naming

---

Dockerfile.kernel
data/dashboards_in_a_nutshell.ipynb
data/lorenz.ipynb
data/variable_inspector.ipynb
public/js/dashboard.js
public/js/widget-manager.js

[Issue: 53] Widget display data fixes

---

app/notebook-store.js

[Issue 74] - Filter hidden files from the notebook list.

---

app/handlebars-helpers.js
data/test_style_match.ipynb
less/dashboard.less
less/rendered-html.less
less/style.less

This will fix many cases involving markdown cells. 
This should also fix text getting cut off on the bottom in certain cases.
Resolves #84

[Issue 84] Use some rendered_html styles from notebook.

---

public/js/dashboard.js
public/js/widget-manager.js

Partial fix. Still fails to stack widgets vertically.
Ref #85

[issue: 85] Render multiple widgets

---

gulpfile.js
less/rendered-html.less
less/style.less
less/variables.less
package.json
public/js/dashboard.js
views/dashboard.handlebars
views/list.handlebars
views/login.handlebars

Adds table styling and introduces bootstrap CSS compilation.
Resolves #83

[Issue 83] Fix look of `test_widget_overlap` dashboard.

---

app/handlebars-helpers.js
less/common.less
less/list.less
less/variables.less
routes/routes.js
views/list.handlebars
views/partials/nav.handlebars

Resolves #87 and partially fulfills #88 (list page).
This PR depends on #96 being merged first.

[Issue 87] Style navbar and dashboard list

---

config.json
less/login.less
routes/login.js
views/login.handlebars
views/partials/nav.handlebars

Resolves #88
This PR depends on #98 being merged first.

[Issue 88] Style login page

---

bower.json
public/js/gridstack-custom.js

Replaces #101 which had a merge conflict.

Update to Gridstack v0.2.4

---

public/js/dashboard.js

[Issue 93] Apply rendered_html class when data is 'text/html'

---

less/common.less
less/variables.less
public/js/dashboard.js
public/js/error-indicator.js
views/partials/nav.handlebars

[Issue 59] Error indicator in navbar

---

less/dashboard.less

This is a minimal change to resolve #109.

[Issue 109] Hide empty widget subarea

---

less/common.less
less/variables.less
package.json
public/js/dashboard.js
public/js/error-indicator.js
routes/routes.js
views/dashboard.handlebars
views/partials/nav.handlebars

Resolves #95, depends on PR #59

[Issue 95] Show a link to dashboard list when viewing index.ipynb

---

Makefile

[Dev] Fix logging-container typo in Makefile

---

Dockerfile.kernel
Dockerfile.server
Makefile
gulpfile.js
package.json
public/js/dashboard.js
public/js/kernel.js
public/js/widget-manager.js

Simple (non-ipywidgets) and declwidgets notebooks are all working.
jupyter-js-widgets needs to be updated (services-shim.js) for those
to work as well.
Ref #40

[Issue 40] Update to jupyter-js-services 0.5

---

app.js
app/config.js
app/handlebars-helpers.js
app/notebook-store.js
config.json
routes/api.js
routes/presentation.js
routes/renderers.js
routes/routes.js
routes/url-to-dashboard.js
test/base/app/upload-notebook-test.js
views/layouts/main.handlebars
views/list.handlebars

PRESENTATION_MODE config option
/dashboard-plain/* route for individual case
Resolves  #99

[Issue 99] Disable chrome

---

app/auth-token.js
test/integration/auth-token/auth-token-test.js

`Authorization: token <value>` like Github
Fixes #127

[issue: 127] Fix upload authorization header format

---

app/notebook-store.js
routes/auth-routes.js
routes/renderers.js

Ensure that we're always storing/getting using same path
from request.
Fixes #150

[Issue 150] Fix caching of notebook data

---

routes/renderers.js

[issue: 149] Separate dashboard title from **/index.ipynb

---

.gitignore
CHANGELOG.md
package.json

* Changelog
* Version bump to 0.4.0
* Then version bump to 0.5.0

0.4.0 release

---

app/config.js
bin/www
routes/api.js

Configure /api proxy with SSL options

---

.cfignore
package.json

cfignore and engine declaration

Some niceties for Cloud Foundry deployment

---

less/dashboard.less
less/notebook.less
less/style.less

[Issue 162] Fix cell styling, compared to Notebook

---

routes/presentation.js

Allow dashboard access at / in presentation mode

---

less/dashboard.less
routes/renderers.js
views/dashboard.handlebars

[Issue 145] Fix notebook dashboards with no layout in metadata

---

app.js
package.json

Implements #171 to store session data using Express cookie-sessions
(c) Copyright IBM Corp. 2016

[issue: 171] Use cookie session storage

---

app/ws-rewriter.js
routes/api.js

Fix KG authorization header missing

---

app/config.js
app/handlebars-helpers.js
data/INTRO/index.ipynb
etc/notebooks/demo/dashboards_in_a_nutshell.ipynb
etc/notebooks/demo/lorenz.ipynb
etc/notebooks/test/test_busy_indicator.ipynb
etc/notebooks/test/test_clear_output.ipynb
etc/notebooks/test/test_env_vars.ipynb
etc/notebooks/test/test_html_javascript.ipynb
etc/notebooks/test/test_layout.ipynb
etc/notebooks/test/test_layout_basic_report.ipynb
etc/notebooks/test/test_markdown.ipynb
etc/notebooks/test/test_plotting_libs.ipynb
etc/notebooks/test/test_style_match.ipynb
etc/notebooks/test/test_widget_overlap.ipynb
less/dashboard.less
public/js/dashboard.js
public/js/layout.js
routes/renderers.js
views/dashboard.handlebars

[Issue 157] Support report layout

---

client/js/dashboard.js
client/js/widget-manager.js

Some minor cleanup left over from ipywidget 5.0 PR.

Properly handle declwidgets init promise failure

---

app.js
package.json

Follow up to #171 
(c) Copyright IBM Corp. 2016

Remove unused dependencies, follow up to #171

---

client/js/dashboard.js

Handle new require.js modules/paths required by latest declwidgets

---

README.md
bin/jupyter-dashboards-server

* README updates
* Log a message on server start

[issue 206] Post release improvements

---

Dockerfile.kernel
README.md
client/js/dashboard.js
client/js/widget-manager.js
client/less/notebook.less
etc/notebooks/test/test_layout_basic.ipynb
package.json

Also contains fix for running scripts on Safari.
Fixes #141

Update jupyter dependencies to latest

---

app/ws-rewriter.js
test/base/app/ws-rewriter-test.js

Fixes #210 
@parente: Test this when you get a chance.

Ensure outgoing WS msgs are handled in order

---

client/js/dashboard.js

Suppress declarative widget errors

---

app/ws-rewriter.js
test/base/app/ws-rewriter-test.js

Filter 'code' prop on 'execute_input' replies to client

---

client/less/notebook.less
etc/notebooks/test/test_style_match_grid.ipynb
etc/notebooks/test/test_style_match_report.ipynb

Add padding on text-cells to match Notebook

---

client/less/common.less
client/less/dashboard.less
client/less/list.less
client/less/notebook.less
client/less/variables.less
views/dashboard.handlebars
views/error.handlebars
views/list.handlebars
views/partials/nav.handlebars

Use bootstrap's 'container' class, to match Notebook style

---

app/notebook-upload.js
package.json

Cleanup same-name dashboards

---

client/js/dashboard.js

... which no longer returns a Promise.
Fixes #229

Support new declwidgets init API

---

Makefile

Use docker links, not public IPs

Fix use of docker-machine for integration test

---

Dockerfile.kernel
client/js/dashboard.js
client/js/kernel.js
client/js/widget-manager.js
etc/notebooks/test/test_scala_hello_world.ipynb
routes/api.js
views/dashboard.handlebars

[Issue: 169] Frontend hardcodes python3

---

.dockerignore
.travis.yml
Dockerfile.server
Makefile

Really want integration + unit to run

Run unit + integration tests on travis

---

Dockerfile.kernel

Can't use Dockerfile ARGs on travis yet.
Using ENV for now instead.

Fix bad merge that broke travis build

---

CHANGELOG.md

Based on the 0.5.x .. master diff.

[no ci] Update changelog for 0.6.0

---

app.js
app/config.js
config.json

Don't silently use a fixed, insecure default

Generate session secret if blank

---

client/js/dashboard.js
etc/notebooks/test/test_markdown.ipynb
test/integration/default/dashboard-widget-test.js

Render markdown from code execution

---

client/js/layout.js
etc/notebooks/test/test_padding.ipynb

* Keep padding, but change values
* Handle rendered_html case
For #246

Another attempt at fixing cell padding

---

Makefile
app/ws-rewriter.js

Allow for large data transfers between browser and kernel

Increase websocket fragment, message sizes

---

app/ws-rewriter.js

The websocket lib has a buffering logger which doesn't print out ws info in time with other logging messages. This PR overrides with the standard `debug` logger we use elsewhere.
To enable ws logging, add `websocket:*` to `start-logging` script in *package.json*.

Override WS logging with non-buffering version

---

Dockerfile.kernel

Rebundle w/ decl widget 0.6.0.dev2

---

Makefile
app/notebook-delete.js
app/renderers.js
routes/auth-routes.js
routes/presentation.js
routes/routes.js
test/integration/default/delete-notebook-test.js
test/integration/default/notebook-list-test.js
test/integration/it-util.js

Adds integration test and fixes some others
Fixes #250

Adds ability to delete dashboards (notebooks)

---

app/ws-rewriter.js
config.json
routes/api.js

... pulled from config.json
Fixes #264

Adds auth and/or extra headers to downstream requests

---

client/js/dashboard.js
client/js/kernel.js

Show busy bar during kernel start. Show error indicator when kernel fails to start.
Fixes #269

Busy / error improvements

---

etc/notebooks/test/test_plotting_libs.ipynb

v0.12 breaks in our current codebase
Ref #279

Pins bokeh lib to v0.11.1

---

app/config.js

Allows read only NOTEBOOKS_DIR v2

---

Dockerfile.kernel

This will add support for the `explore` function

Bump declarative widgets version in kernel dockerfile.

---

Makefile
README.md
app.js
app/config.js
app/public-link.js
app/renderers.js
app/ws-rewriter.js
bin/jupyter-dashboards-server
client/js/kernel.js
client/less/variables.less
config.json
etc/nginx/nginx.vh.default.conf
gulpfile.js
package.json
routes/api.js
views/dashboard.handlebars
views/layouts/main.handlebars
views/list.handlebars
views/login.handlebars
views/partials/nav.handlebars

Ref #260
Based on PR #291 by @danielfrg

Support a 'prefix' url under which to run server (i.e. for proxies)

---

app/auth-auth0.js

This PR adds a simple auth from Auth0.

Add authentication from Auth0

---

README.md

* Call out which libraries work more clearly
* Link to new wiki page about adding widget support
* Move Thebe information to wiki
* General formatting improvements
* Add npm release badge
* Remove duplicate workflow info

Some README cleanup

---

app/auth-ldap.js

Added a small module for using ldap to authorize users

add auth module for the ldap protocol
